"""Feature inference step for eval/serve modes."""

from __future__ import annotations

from typing import Any, Dict, List, Optional

import numpy as np
import pandas as pd

from mlproject.src.pipeline.steps.base import BasePipelineStep
from mlproject.src.pipeline.steps.factory_step import StepFactory


class FeatureInferenceStep(BasePipelineStep):
    """Generate features from loaded model in eval/serve mode.

    This step is auto-generated by ConfigGenerator for eval/serve
    pipelines when feature_pipeline is declared in train config.

    It handles:
    1. Loading base features from context
    2. Using loaded model to generate features
    3. Storing features in specified output_key

    This eliminates manual inference step creation and ensures
    consistency between train/eval/serve pipelines.
    """

    def __init__(
        self,
        step_id: str,
        cfg: Any,
        enabled: bool = True,
        depends_on: Optional[List[str]] = None,
        source_model_key: str = "model",
        base_features_key: str = "preprocessed_data",
        output_key: str = "features",
        **kwargs: Any,
    ) -> None:
        """Initialize feature inference step.

        Parameters
        ----------
        step_id : str
            Unique step identifier.
        cfg : Any
            Configuration object.
        enabled : bool
            Whether step should execute.
        depends_on : Optional[List[str]]
            Prerequisite steps.
        source_model_key : str
            Context key for source model.
        base_features_key : str
            Context key for base features.
        output_key : str
            Context key to store generated features.
        **kwargs
            Additional parameters.
        """
        super().__init__(step_id, cfg, enabled, depends_on, **kwargs)
        self.source_model_key = source_model_key
        self.base_features_key = base_features_key
        self.output_key = output_key

    def execute(self, context: Dict[str, Any]) -> Dict[str, Any]:
        """Execute feature generation.

        Parameters
        ----------
        context : Dict[str, Any]
            Pipeline context.

        Returns
        -------
        Dict[str, Any]
            Context with generated features added.

        Raises
        ------
        KeyError
            If required model or features not found.
        """
        self.validate_dependencies(context)

        # Get model
        model = context.get(self.source_model_key)
        if model is None:
            raise KeyError(
                f"Step '{self.step_id}': Model key "
                f"'{self.source_model_key}' not found in context"
            )

        # Get base features
        base_features = context.get(self.base_features_key)
        if base_features is None:
            raise KeyError(
                f"Step '{self.step_id}': Base features key "
                f"'{self.base_features_key}' not found in context"
            )

        # Prepare input
        x = self._prepare_input(base_features)

        # Generate features
        print(
            f"[{self.step_id}] Generating features from " f"'{self.source_model_key}'"
        )
        print(f"  Input shape: {x.shape}")

        features = model.predict(x)

        print(f"  Output shape: {features.shape}")

        # Store in context
        context[self.output_key] = features

        print(f"[{self.step_id}] Stored features in '{self.output_key}'")

        return context

    def _prepare_input(self, features: Any) -> np.ndarray:
        """Prepare input for model prediction.

        Parameters
        ----------
        features : Any
            Raw features (DataFrame, ndarray, etc).

        Returns
        -------
        np.ndarray
            Prepared input array.
        """

        if isinstance(features, pd.DataFrame):
            return features.values.astype(np.float32)

        if isinstance(features, np.ndarray):
            return features.astype(np.float32)

        if isinstance(features, (list, tuple)):
            return np.array(features, dtype=np.float32)

        raise TypeError(f"Unsupported feature type: {type(features).__name__}")


StepFactory.register("feature_inference", FeatureInferenceStep)
